DB_synthetic: "/home/s5xu/projects/data/db/synthetic"
DB_N: "/projects/ps-yeolab3/bay001/annotations/nr/nt"
DB_X: "/projects/ps-yeolab3/bay001/annotations/nr/nr.dmnd"


N_downsample_reads: 100

SAMPLESPATH:
  - "samplefiles/Cas711_SE_GRCh38.Apo_Cas711_input_r1.umi.r1.fq.genome-mapped.bam"
  - "samplefiles/Cas711_SE_GRCh38.EEF1A1_22nt_Cas711_IP_r1.umi.r1.fq.genome-mapped.bam"
